version: 1
defaults:
  backend: original
  fallback_backend: original
  disable_backend_on_first_failure: true
ops:
  RMSNorm:
    backend: infinicore
  GemmaRMSNorm:
    backend: infinicore
  SiluAndMul:
    backend: ninetoothed
  ApplyRotaryEmb:
    backend: ninetoothed
  Embedding:
    backend: ninetoothed
  TopKTopP:
    backend: ninetoothed
  RandomSample:
    backend: ninetoothed
  MatMul:
    backend: original
  LMHead:
    backend: original
  StoreKVCache:
    backend: original
  PagedAttentionPrefill:
    backend: original
  PagedAttentionDecode:
    backend: original
  SDPA:
    backend: original
